module("SoraConstant", package.seeall)

local httpStatusCode = {
	HTTP_CONTINUE = 100,
	HTTP_SWITCHING_PROTOCOLS = 101,
	HTTP_OK = 200,
	HTTP_CREATED = 201,
	HTTP_ACCEPTED = 202,
	HTTP_NO_CONTENT = 204,
	HTTP_PARTIAL_CONTENT = 206,
	HTTP_SPECIAL_RESPONSE = 300,
	HTTP_MOVED_PERMANENTLY = 301,
	HTTP_MOVED_TEMPORARILY = 302,
	HTTP_SEE_OTHER = 303,
	HTTP_NOT_MODIFIED = 304,
	HTTP_TEMPORARY_REDIRECT = 307,
	HTTP_BAD_REQUEST = 400,
	HTTP_UNAUTHORIZED = 401,
	HTTP_PAYMENT_REQUIRED = 402,
	HTTP_FORBIDDEN = 403,
	HTTP_NOT_FOUND = 404,
	HTTP_NOT_ALLOWED = 405,
	HTTP_NOT_ACCEPTABLE = 406,
	HTTP_REQUEST_TIMEOUT = 408,
	HTTP_CONFLICT = 409,
	HTTP_GONE = 410,
	HTTP_UPGRADE_REQUIRED = 426,
	HTTP_TOO_MANY_REQUESTS = 429,
	HTTP_CLOSE = 444,
	HTTP_ILLEGAL = 451,
	HTTP_INTERNAL_SERVER_ERROR = 500,
	HTTP_METHOD_NOT_IMPLEMENTED = 501,
	HTTP_BAD_GATEWAY = 502,
	HTTP_SERVICE_UNAVAILABLE = 503,
	HTTP_GATEWAY_TIMEOUT = 504,
	HTTP_VERSION_NOT_SUPPORTED = 505,
	HTTP_INSUFFICIENT_STORAGE = 507,
}

function httpStatusStringByCode(statusCode)
	for name,code in pairs(httpStatusCode) do
		if code == statusCode then
			return name
		end
	end
	return nil
end

return SoraConstant
